language: java
jdk:
  - openjdk8
  - openjdk11
install: mvn install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script: mvn cobertura:cobertura -B
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)

